### ISSUE TITLE
Upgrade logdna module to @logdna/logger module

### ISSUE THREAD

**Issue by bailey-byb** [logdna/logdna-winston#21]
Currently this module is using the deprecated `logdna` module instead of `@logdna/logger`. it should be upgraded.

**Comment by darinspivey** [comment]
Sure thing, thanks for reporting this.  All such dependencies will be upgraded very soon.  We were just letting the new version burn in a bit, and undergo some additions to support our own internal needs.  All that is wrapping up now.

**Comment by smusali** [comment]
@bailey-byb, this has been upgraded in #22 and released as `v3.0.0`. Thanks again for reporting this!
