### ISSUE TITLE
winston 3 support?

### ISSUE THREAD

**Issue by bonesoul** [logdna/logdna-winston#3]
https://github.com/winstonjs/winston/issues/1331

**Comment by Jolg42** [comment]
Indeed.... Please upgrade! 😉 

The migration doc is there:
https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md

**Comment by mattposch** [comment]
what's the state on this?

**Comment by jnystrom** [comment]
So this does not work with Winston 3 at all?

**Comment by dougwt** [comment]
I found this in the winston 3 docs about how to create custom Transports, but I am not familiar enough with the mechanics of winston to implement the changes myself:
https://github.com/winstonjs/winston#adding-custom-transports

**Comment by Need-To-Learn** [comment]
Hi, winston 3 compatibility would be nice !

**Comment by bonesoul** [comment]
I still can't move to winston 3 just because of this module.

**Comment by LYHuang** [comment]
Support Winston 3 now.

**Comment by lgfa29** [comment]
@LYHuang I am still getting the upgrade message when using Winston 3. The `log` function parameters have changed in Winston 3.

I opened #8 to fix this.
